### ISSUE TITLE
Support SET command

### ISSUE THREAD

**Issue by Marco-Santoni** [fphilipe/psql2csv#1]
What if one wants to run a `SET` command before the query? E.g.

``` sql
-- test.sql
SET timezone TO 'UTC';
SELECT * FROM users;
```

Then, the following won't work:

``` bash
$ < test.sql  psql2csv db_name > test.csv
```

As the `SET` is also wrapped inside `COPY`:

```
ERROR:  syntax error at or near "SET"
LINE 1: COPY  ( SET timezone= 'UTC' ; SELECT * FROM...
```

**Comment by fphilipe** [comment]
That's not supported. Only one single query can be executed at a time. One possible workaround in your specific case is to change the DB default to be UTC or to select `timezone('UTC', column)`.

Alternatively we could support an argument which in itself is a query that gets run before the copy query, kind of like a setup. WDYT?

**Comment by fphilipe** [comment]
Version 0.9 has a new `--timezone` and `--search-path` option.
